
server:
  port: 8000
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  main:
    web-application-type: reactive

  r2dbc:
    protocol: mariadb
    host: ${MARIA_DB_HOST:localhost}
    port: ${MARIA_DB_PORT:3306}
    database: ${MARIA_DB_DATABASE:test}
    username: ${MARIA_DB_USERNAME:root}
    password: ${MARIA_DB_PASSWORD:pass}

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASS}

  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:test}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:pass}

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

jwt:
  secret-key: ${JWT_SECRET_KEY:tmp}
  access-exp: ${JWT_ACCESS_EXP:1000000}
  refresh-exp: ${JWT_REFRESH_EXP:1000000}

auth:
  base-url: ${GOOGLE_BASE_URL:tmp}
  redirect-url: ${REDIRECT_URL:tmp}
  client-id: ${GOOGLE_CLIENT_ID:tmp}
  secret-key: ${GOOGLE_SECRET_KEY:tmp}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:tmp}
    secret-key: ${AWS_SECRET_ACCESS_KEY:tmp}
  s3:
    url: ${AWS_S3_URL:tmp}
    bucket: ${AWS_S3_BUCKET:tmp}
    profile-folder: ${PROFILE_FOLDER:tmp}
    document-folder: ${DOC_FOLDER:tmp}
    pdf-folder: ${PDF_FOLDER:tmp}

domain:
  school:
    year:
      id: ${SCHOOL_YEAR_ID}
      secret: ${SCHOOL_YEAR_ADMIN_KEY:tmp}

sentry:
  dsn: ${SENTRY_DSN:tmp}
  traces-sample-rate: 1.0

log:
  stash:
    name: satellite.log
    path: ${LOG_PATH:/}
    size: 10
