server:
  port: 8000
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}

  jpa:
    hibernate:
      ddl-auto: ${DDL:validate}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASS}

  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:test}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:pass}

  thymeleaf:
    prefix: classpath:/templates

  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: ${JWT_SECRET_KEY:tmp}
  access-exp: ${JWT_ACCESS_EXP:1000000}
  refresh-exp: ${JWT_REFRESH_EXP:1000000}

auth:
  base-url: ${GOOGLE_BASE_URL:tmp}
  redirect-url: ${REDIRECT_URL:tmp}
  client-id: ${GOOGLE_CLIENT_ID:tmp}
  secret-key: ${GOOGLE_SECRET_KEY:tmp}

cloud:
  aws:
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:tmp}
      secret-key: ${AWS_S3_SECRET:tmp}
  ses:
    access-key: ${AWS_SES_ACCESS:tmp}
    secret-key: ${AWS_SES_SECRET:tmp}

aws:
  s3:
    url: ${AWS_S3_URL:tmp}
    bucket: ${AWS_S3_BUCKET:tmp}
    profile-folder: ${AWS_S3_PROFILE_FOLDER:repo-pof}
    document-folder: ${AWS_S3_DOC_FOLDER:repo-doc}
    pdf-folder: ${AWS_S3_PDF_FOLDER:repo-pdf}
  ses:
    access-key: ${AWS_SES_ACCESS:tmp}
    secret-key: ${AWS_SES_SECRET:tmp}
    region: ${AWS_SES_REGION:tmp}

cool-sms:
  key: ${SMS_KEY:tmp}
  secret: ${SMS_SECRET:tmp}
  phoneNumber: ${SMS_PHONE_NUMBER:01012345678}

domain:
  school:
    year:
      id: ${SCHOOL_YEAR_ID}
      secret: ${SCHOOL_YEAR_ADMIN_KEY}
