server:
  port: 8000
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  datasource:
    username: ${DB_USERNAME:cos}
    password: ${DB_PASSWORD:cos1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}

  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_URL:localhost}:27017
      database: ${MONGO_DB_NAME}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}

redis:
  port: ${REDIS_PORT}
  host: ${REDIS_HOST}
  password: ${REDIS_PASS}

auth:
  base-url: ${GOOGLE_BASE_URL}
  redirect-url: ${REDIRECT_URL}
  client-id: ${GOOGLE_CLIENT_ID}
  secret-key: ${GOOGLE_SECRET_KEY}

cloud:
  aws:
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:s3_access}
      secret-key: ${AWS_S3_SECRET:s3_secret}

aws:
  s3:
    url: ${AWS_S3_URL:https://}
    bucket: ${AWS_S3_BUCKET:bucket}
    profile-folder: ${AWS_S3_PROFILE_FOLDER:pro-image/}
    document-folder: ${AWS_S3_PREVIEW_FOLDER:doc-image/}

verification:
  phone:
    limit-count-of-send: ${PHONE_LIMIT_COUNT}
    base-time-to-live: ${PHONE_EXP}
    code-length: ${PHONE_LENGTH}
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    phoneNumber: ${SMS_PHONE_NUMBER}