server:
  port: 8000
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}

  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASS}

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:test}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:pass}

jwt:
  secret-key: ${JWT_SECRET_KEY:tmp}
  access-exp: ${JWT_ACCESS_EXP:1000000}
  refresh-exp: ${JWT_REFRESH_EXP:1000000}

auth:
  base-url: ${GOOGLE_BASE_URL:tmp}
  redirect-url: ${REDIRECT_URL:tmp}
  client-id: ${GOOGLE_CLIENT_ID:tmp}
  secret-key: ${GOOGLE_SECRET_KEY:tmp}

cloud:
  aws:
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:s3_access}
      secret-key: ${AWS_S3_SECRET:s3_secret}

aws:
  s3:
    url: ${AWS_S3_URL:https://}
    bucket: ${AWS_S3_BUCKET:bucket}
    profile-folder: ${AWS_S3_PROFILE_FOLDER:pro-image/}
    document-folder: ${AWS_S3_PREVIEW_FOLDER:doc-image/}

cool-sms:
  key: ${SMS_KEY:tmp}
  secret: ${SMS_SECRET:tmp}
  phoneNumber: ${SMS_PHONE_NUMBER:01012345678}

domain:
  auth:
    code:
      limit-count-of-send: ${PHONE_LIMIT_COUNT:10}
      time-to-live: ${PHONE_EXP:100000}