name: satellite - CD

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: build docker image
        run: docker build -t rolls .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: satellite
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}