name: satellite - CD

on:
  push:
    branches: [ master ]

jobs:
  CD:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --build-cache
            --no-daemon
            
      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master 
        with:
          environment: prod
          access_key: ${{ secrets.ACCESS_KEY }}
          github_token: ${{ secrets.GHP_TOKEN }} 
          buildargs: |
            DB_HOST=${{ secrets.DB_HOST }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_SECRET_KEY=${{ secrets.GOOGLE_SECRET_KEY }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            MARIA_DB_PASSWORD=${{ secrets.MARIA_DB_PASSWORD }}
            MARIA_DB_PORT=${{ secrets.MARIA_DB_PORT }}
            MARIA_DB_USERNAME=${{ secrets.MARIA_DB_USERNAME }}
            MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}
            MONGO_DB_USERNAME=${{ secrets.MONGO_DB_USERNAME }}
            SCHOOL_YEAR_ID=${{ secrets.SCHOOL_YEAR_ID }}
            SCHOOL_YEAR_ADMIN_KEY=${{ secrets.SCHOOL_YEAR_ADMIN_KEY }}
