name: satellite - CD

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --build-cache
            --no-daemon
            
      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master 
        with:
          environment: prod
          access_key: ${{ secrets.ACCESS_KEY }}
          github_token: ${{ secrets.GHP_TOKEN }} 
          buildargs: |
            CLOUD_CONFIG_PASSWORD=${{secrets.CLOUD_CONFIG_PASSWORD}}
            CLOUD_CONFIG_USERNAME=${{secrets.CLOUD_CONFIG_USERNAME}}
            PROFILE=prod
